{
    "name": "Restaurant Accounting",
    "summary": "Audited purchase-to-pay and restaurant accounting workflows",
    "version": "20.0.1.0.0",
    "category": "Accounting",
    "license": "LGPL-3",
    "author": "Restaurant Project",
    "depends": [
        "restaurant_core",
        "restaurant_stock",
        "restaurant_reception",
        "account",
        "purchase_stock",
        "mail",
    ],
    "data": [
        "security/restaurant_accounting_security.xml",
        "security/ir.access.csv",
        "data/ir_sequence_data.xml",
        "views/restaurant_purchase_invoice_handoff_views.xml",
        "views/restaurant_daily_sales_accounting_views.xml",
        "views/restaurant_accounting_period_close_views.xml",
        "views/restaurant_accounting_settings_views.xml",
        "views/restaurant_accounting_menus.xml",
        "views/restaurant_management_dashboard_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "application": False,
    "installable": True,
}
