from . import restaurant_daily_closing
from . import restaurant_staff_category
from . import hr_employee
from . import employee_branch_assign_wizard
from . import employee_staff_category_assign_wizard
from . import restaurant_waiter_daily_line
from . import restaurant_attendance_entry
from . import restaurant_leave_request
from . import restaurant_closing_finance
from . import restaurant_service_entry
from . import restaurant_waiter_sales_closing
from . import restaurant_hr_sync
from . import restaurant_attendance_sheet
